spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5433/bank-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

server:
  port: 8080

---
spring:
  profiles: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2://mem:db
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
